wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.10
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688998618.332406
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 24
      4: 3.7.10
      5: 0.15.5
      8:
      - 5
