home = '/home/songran/'
work_dir = './work_dir/'
data_config_root = './dataset_config_file/'
dataset_root='/data/songran/lads-project/lads-dataset/'
extra_lib_path = '/opt/hf_venvs/python3.8/202109/lib/python3.8/site-packages'
image_root_referit = '/data/songran/datasets/saiaprtc12'